config/routes.rb
PhoneTexter::Application.routes.draw do
  resources :apps do
    member do
      get 'download'
    end
  end

  match 'sms' => 'sms#send_sms'
  match 'phone_texter' => 'form_builder#build'
  match 'demo' => 'static_pages#demo'
  match 'demo_without' => 'static_pages#demo_without'
  
  root :to => 'apps#new'

end

app/models/app.rb
class App < ActiveRecord::Base
  attr_accessible :android_url, :blackberry_url, :ios_url, :name, :other_url
  
  validates :name, :presence => true
  validates_format_of :other_url, :with => URI::regexp(%w(http https))
  validates_format_of :android_url, :with => URI::regexp(%w(http https)), :allow_blank => true
  validates_format_of :ios_url, :with => URI::regexp(%w(http https)), :allow_blank => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  
  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apps }
    end
  end
  
  def download
    @app = App.find(params[:id])
    
    if request.user_agent =~ /iPhone|iPad/
      redirect_to @app.ios_url
    elsif request.user_agent =~ /Android/
      redirect_to @app.android_url
    elsif request.user_agent =~ /BlackBerry/
      redirect_to @app.blackberry_url
    else
      redirect_to @app.other_url
    end
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    @app = App.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/new
  # GET /apps/new.json
  def new
    @app = App.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/1/edit
  def edit
    @app = App.find(params[:id])
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(params[:app])
    if @app.save
      redirect_to @app, notice: 'Success!'
    else
      render action: "new"
    end
  end

  # PUT /apps/1
  # PUT /apps/1.json
  def update
    @app = App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app = App.find(params[:id])
    @app.destroy

    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/form_builder_controller.rb
class FormBuilderController < ApplicationController
  def build
    @id = params[:id]
    render 'phone_texter.js'
  end
end

app/controllers/sms_controller.rb
class SmsController < ApplicationController
  
  def send_sms
    @client = Twilio::REST::Client.new TWILIO['account_sid'], TWILIO['auth_token']
    @number = params[:number]
    @app = App.find(params[:id])
    @client.account.sms.messages.create(
      :from => '+16464900357',
      :to => @number,
      :body => 'Download ' + @app.name + " " + download_app_url(@app),
    )
    render :confirm
  end
  
  def confirm
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @app = App.new
  end
  
  def demo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/form_builder_helper.rb
module FormBuilderHelper
end

app/helpers/sms_helper.rb
module SmsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/apps/_form.html.erb
<div class="row">
	<div class="span6 offset3">
<%= form_for(@app) do |f| %>
  <%= render 'shared/error_messages' %>

    <%= f.label :name, 'Your App Name' %>
    <%= f.text_field :name %>

    <%= f.label :other_url, 'Default Mobile URL' %>
    <%= f.text_field :other_url, :placeholder => 'http://mobilesite.com' %>

    <%= f.label :ios_url, 'URL for iPhone Users' %>
    <%= f.text_field :ios_url, :placeholder => 'http://itunes.apple.com/us/app/...' %>

    <%= f.label :android_url, 'URL for Android Users' %>
    <%= f.text_field :android_url, :placeholder => 'https://play.google.com/store/apps/...' %>

    <%= f.submit "Create embed code", class: "btn btn-large btn-primary"%>
<% end %>
</div>
</div>

app/views/apps/download.html.erb
<p>
  <b>Name:</b>
  <%= @app.name %>
</p>

<p>
  <b>Ios url:</b>
  <%= @app.ios_url %>
</p>

<p>
  <b>Android url:</b>
  <%= @app.android_url %>
</p>

<p>
  <b>Blackberry url:</b>
  <%= @app.blackberry_url %>
</p>

<p>
  <b>Other url:</b>
  <%= @app.other_url %>
</p>

<p>
  <b>Embed code:</b>
  <%= html_escape('<script type="text/javascript" src="http://morning-spire-1524.herokuapp.com/phone_texter?id=') %><%= @app.id%><%= html_escape('"></script>') %>
</p>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th>ID</th>
		<th>Name</th>
    <th>Ios url</th>
    <th>Android url</th>
    <th>Blackberry url</th>
    <th>Other url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= app.id %></td>
		<td><%= app.name %></td>
    <td><%= app.ios_url %></td>
    <td><%= app.android_url %></td>
    <td><%= app.blackberry_url %></td>
    <td><%= app.other_url %></td>
    <td><%= link_to 'Show', app %></td>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<div class="center hero-unit">
  <h1>Welcome to App Texts</h1>

  <h2>
    Put your app info below and we'll give you code to embed. Users will get a text directing them to a mobile download page. <%= link_to "Here's a demo", "demo" %> of what it looks like.
  </h2>
</div>

  <%= render 'form' %>

app/views/apps/show.html.erb
<div class="center hero-unit">
	<h1>Now embed this code</h1>
	<p>
  <% code = '<script type="text/javascript" src="http://apptexts.herokuapp.com/phone_texter?id=' + @app.id.to_s + '"></script>' %>

	<%= html_escape(code) %>
	
</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App Texts</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "app texts", '#', id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to "Home",    '#' %></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @app.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@app.errors.count, "error") %>.
    </div>
    <ul>
    <% @app.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/sms/confirm.html.erb
<div class="center hero-unit">
<h1>Confirmed!</h1>
<p>Text sent to <%= @number %></p>
</div>

app/views/static_pages/demo.html.erb
  <h1>Demo App</h1>

  <h2>
    Open app.com/download in your phone’s browser or <b>text it to your phone</b>
  </h2>

<script type="text/javascript" src="http://apptexts.herokuapp.com/phone_texter?id=1"></script>

app/views/static_pages/demo_without.html.erb
  <h1>Demo App</h1>

  <h2>
    Open app.com/download in your phone’s browser
  </h2>

app/views/static_pages/home.html.erb
<h1>Home</h1>